/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IdentitiesIndexImport } from './routes/identities/index'
import { Route as HostsIndexImport } from './routes/hosts/index'
import { Route as TerminalsIdImport } from './routes/terminals/$id'

// Create/Update Routes

const IdentitiesIndexRoute = IdentitiesIndexImport.update({
  id: '/identities/',
  path: '/identities/',
  getParentRoute: () => rootRoute,
} as any)

const HostsIndexRoute = HostsIndexImport.update({
  id: '/hosts/',
  path: '/hosts/',
  getParentRoute: () => rootRoute,
} as any)

const TerminalsIdRoute = TerminalsIdImport.update({
  id: '/terminals/$id',
  path: '/terminals/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminals/$id': {
      id: '/terminals/$id'
      path: '/terminals/$id'
      fullPath: '/terminals/$id'
      preLoaderRoute: typeof TerminalsIdImport
      parentRoute: typeof rootRoute
    }
    '/hosts/': {
      id: '/hosts/'
      path: '/hosts'
      fullPath: '/hosts'
      preLoaderRoute: typeof HostsIndexImport
      parentRoute: typeof rootRoute
    }
    '/identities/': {
      id: '/identities/'
      path: '/identities'
      fullPath: '/identities'
      preLoaderRoute: typeof IdentitiesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/terminals/$id': typeof TerminalsIdRoute
  '/hosts': typeof HostsIndexRoute
  '/identities': typeof IdentitiesIndexRoute
}

export interface FileRoutesByTo {
  '/terminals/$id': typeof TerminalsIdRoute
  '/hosts': typeof HostsIndexRoute
  '/identities': typeof IdentitiesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/terminals/$id': typeof TerminalsIdRoute
  '/hosts/': typeof HostsIndexRoute
  '/identities/': typeof IdentitiesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/terminals/$id' | '/hosts' | '/identities'
  fileRoutesByTo: FileRoutesByTo
  to: '/terminals/$id' | '/hosts' | '/identities'
  id: '__root__' | '/terminals/$id' | '/hosts/' | '/identities/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  TerminalsIdRoute: typeof TerminalsIdRoute
  HostsIndexRoute: typeof HostsIndexRoute
  IdentitiesIndexRoute: typeof IdentitiesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  TerminalsIdRoute: TerminalsIdRoute,
  HostsIndexRoute: HostsIndexRoute,
  IdentitiesIndexRoute: IdentitiesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/terminals/$id",
        "/hosts/",
        "/identities/"
      ]
    },
    "/terminals/$id": {
      "filePath": "terminals/$id.tsx"
    },
    "/hosts/": {
      "filePath": "hosts/index.tsx"
    },
    "/identities/": {
      "filePath": "identities/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
